version: '3'

services:
  api:
    image: registry.gitlab.com/abourneron/mobytm-backend-api:latest 
    ports:
      - "8081:3000"
    depends_on:
      - mongo
    environment:
      - URL_MONGO=mongodb://mongo:27080/
    links:
      - mongo

  mongo:
    image: registry.gitlab.com/abourneron/mobytm-backend-mongo:latest
    volumes:
      - "./mongo/data:/data/db"
    ports:
      - "27080:27017"

  front:
    image: registry.gitlab.com/abourneron/mobytm:latest
    ports:
      - "80:80"

