version: '3'

services:
  mongo:
    image: registry.gitlab.com/abourneron/mobytm/back/mongo:latest
    volumes:
      - "./mongo/data:/data/db"
    ports:
      - "27080:27017"

  api:
    image: registry.gitlab.com/abourneron/mobytm/back/api:latest
    ports:
      - "8081:3000"
    depends_on:
      - mongo
    environment:
      - URL_MONGO=mongodb://mongo:27080/
    links:
      - mongo
      
  front:
    image: registry.gitlab.com/abourneron/mobytm/front:latest
    ports:
      - "80:80"


